project:
  type: website
  output-dir: docs

website:
  title: "PSTAT 5A: Archives"

  sidebar:
    title: "PSTAT 5A: Archives"
    style: "docked"
    search: true
    logo: "Images/Logos_Icons/5a_hex.png"

  page-footer: "Site Designed by Ethan Marzban using Quarto; ©2023"
  favicon: "Images/Logos_Icons/5a_hex.png"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
