---
title: "PSTAT 5A: Understanding Data"
subtitle: "Course Syllabus"
author:
  - name: "Ethan Marzban"
    affiliations:
      - name: "Spring 2023"
author-title: "Instructor"
affiliation-title: "Quarter"
format: html
linkcolor: "#ffa07a"
---

**WELCOME TO PSTAT 5A**! I am very excited to introduce to you the wonderful worlds of Statistics and Data Science. As our world becomes ever more saturated with data, the need for data literacy becomes increasingly important. By the end of this course, I hope you will be able to think critically about statistical studies and results, understand how data can be used to simultaneously inform and manipulate, and begin applying your newfound techniques to your future endeavors, all while gaining an introduction to the fields of Statistics and Data Science. I am very much looking forward to a great quarter with all of you!

--- Ethan

## Lecture Information

::: callout-note
## **Lecture Times and Locations**

Tuesdays and Thursdays: 2:00pm - 3:15pm in **CHEM 1171**
:::

## Course Staff

\vspace{-5mm}

::: {layout-ncol="2"}
+-----------------+-----------------------------------------------------------------------+
| **Instructor:** | Ethan P. Marzban                                                      |
+:================+:======================================================================+
| **Email:**      | [epmarzban\@pstat.ucsb.edu](mailto:epmarzban@pstat.ucsb.edu)          |
+-----------------+-----------------------------------------------------------------------+
| **Help Hours:** | -   [**HW Clinic**]{.underline}: Tuesdays 4:30 - 5:30pm in ELLSN 2626 |
|                 | -   [**OH:**]{.underline} Fridays 12-1pm in SH 5607F                  |
+-----------------+-----------------------------------------------------------------------+

: {tbl-colwidths="\[20, 30\]"}

+----------------------------------------------------+
| **TAs**                                            |
+:===================================================+
| **Nickolas Thiessen**\                             |
| ([nickolas\@ucsb.edu](mailto:nickolas@ucsb.edu))   |
+----------------------------------------------------+
| **Jason Teng**\                                    |
| ([jteng\@ucsb.edu](mailto:jteng@ucsb.edu))         |
+----------------------------------------------------+
| **Yuan Zhou**\                                     |
| ([yuan_zhou\@ucsb.edu](mailto:yuan_zhou@ucsb.edu)) |
+----------------------------------------------------+

: {tbl-colwidths="\[50\]"}
:::

## Course Description

The official description of this course, from the Course Catalogue, is:

> Introduction to data science. Concepts of statistical thinking. Topics include random variables, sampling distributions, hypothesis testing, correlation and regression. Visualizing, analyzing and interpreting real world data using Python. Computing labs required.

## Textbook(s)

This quarter, we do not have a required textbook- the lecture slides and lab activities are designed to be self-sufficient. However, the following textbooks are highly recommended:

-   *OpenIntro: Statistics*. David Diez, Mine Çetinkaya-Rundel, and Christopher D Barr. (free version, courtesy of the authors, available at <a href = "https://leanpub.com/os/" target = "_blank">https://leanpub.com/os</a>)

-   *Computational and Inferential Thinking: The Foundations of Data Science*. Ani Adhikari and John DeNero. (available at: <a href = "https://inferentialthinking.com/" target = "_blank">https://www.inferentialthinking.com</a>)

-   *StatClass* (2nd Edition, Revised). Dawn E. Holmes and Lubella A. Lenaburg

## Course Components

The following are the assignments and metrics that will be used to compute your final grade in this course:

### Homework:

There will be **weekly** homework assignments that are each graded out of 10 points, on a combination of **correctness** and **completion**: we will select a few parts/problems to be graded out of 8 points on correctness, and you will be awarded 2 points for completing the remainder of the homework. Your lowest homework score will be dropped.\

Homework assignments will typically be released on Wednesdays and be due on Tuesdays, with the exception of Exam Weeks when the homework will be due on Monday.

### Quizzes

Quizzes will be administered on **Wednesdays, During your Lab Section**. Make-up quizzes will **not** be offered; instead, your lowest quiz score will be dropped at the end of the quarter. There are no quizzes in Exam Weeks.

### Exams

There are **two midterms** and a **final** exam for this class. You are required to take all three exams; failure to do so will result in an automatic grade of "F", so please ensure you are able to take the exams on the dates listed below.

::: callout-note
## **Exam Dates**:

-   Midterm 1 is scheduled to take place **Tuesday, April 25 from 2 - 3:15pm** (lecture time)
-   Midterm 2 is scheduled to take place **Tuesday, May 23 from 2 - 3:15pm** (lecture time)
-   The final is scheduled to take place **Tuesday, June 13 from 4 - 7pm** (as determined by the University)
:::

The midterms are scheduled to take place in **Embarcadero Hall**, and will have assigned seating. [The Final Exam will also take place in **Embarcadero Hall**.]{style="color:red"} Unless stated otherwise, all exams will be cumulative.

### Schedule of Due Dates

A tentative schedule of release and due dates can be found <a href = "https://docs.google.com/spreadsheets/d/1Cd_i_3Ch_l66j_r6cmDfukN_ynb4hEerwmMIyh4buEg/edit?usp=sharing" target = "_blank">here</a>

## Grading Scheme

Your final grade will be computed using the following weights:

|                    |     |
|:-------------------|:----|
| Homework:          | 10% |
| Labs:              | 10% |
| Quizzes:           | 10% |
| Midterm 1          | 20% |
| Midterm 2          | 20% |
| Final Examination: | 30% |

Please note that late submissions for any of the above will **not** be accepted. Instead, I will drop your lowest homework, lab, quiz, and midterm score (you must take all three exams; failure to do so will result in an automatic 'F')

Your final letter grade will be issued according to the following scheme (cutoffs between plusses and minuses will be calculated at the end of the quarter):

-   A^--^ -- A^+^: 90 -- 100%
-   B^--^ -- B^+^: 80 -- 89.99%
-   C^--^ -- C^+^: 70 -- 79.99%
-   D^--^ -- D^+^ : 60 -- 69.99%
-   F: 0 -- 59.99%

Please note: I have elected to adopt an uncurved grading scheme to eliminate any sense of "competition" among students; I highly encourage you all to collaborate with and uplift each other. Having said that, I will certainly consider adjusting the cutoffs (naturally, in everyone's favor) at the end of the quarter if necessary.

## Academic Integrity

As a member of the UCSB community, it is expected that you will act with academic integrity. This means, among other things, that the work you submit should be entirely your own and not copied from any external sources. Collaboration on homework assignments is perfectly acceptable (even encouraged) but the work you submit should still be your own; you can't have someone else write up solutions for you, nor can you consult cites like Chegg, CourseHero, etc. Anyone found guilty of academic misconduct will be reported to the Academic Senate, and will receive at minimum a failing grade on the assignment in question; further actions may also include failing the course, and marks being made on permanent records. Depending on the severity of the infraction, expulsion is also a possibility.

Basically, don't cheat- please! If you're ever struggling with course material, please come talk to me or the TA's. We are truly here for you, and want only the best for you.

## Intellectual Property

You've probably seen a clause on other syllabi stating something to the effect of "all material in this course is the intellectual property of myself and may not be shared with anyone outside this class without my explicit written permission."

Though this is all true, I will be making most course-related material available on a public GitHub site, which can be accessed here: <a href = "https://pstat5a.github.io" target = "_blank">https://pstat5a.github.io</a>.

## Disabled Students Program (DSP)

If you have a disability, or otherwise require accommodations for the exams and/or quizzes please reach out to the Disabled Students Program (DSP) ASAP to ensure your request(s) for accommodation can be processed. We ask that all requests be logged **at least a week in advance**, to ensure the system enough time to process. Please note that we cannot grant any requests for accommodations unless they come to us from DSP directly.

## Technology Needs

As a part of this course, you will be required to program in Python. Though the Lab Sections take place in specially designed classrooms that come equipped with computers, your homework and quizzes may cover Python-related questions, which means we expect you to have access to a laptop capable of connecting to the internet. If you do not currently possess such a laptop, please check out UCSB's Basic Needs Resource [page on Technology Resources](https://food.ucsb.edu/resources/technology-resources) to try and acquire one.

## Section Switching

As mentioned above, Sections (both Discussion and Lab) take place in special "Collaborate Classrooms" which are equipped with laptops. There are a fixed number of seats and laptops in these classrooms, meaning we cannot under any circumstance over-enroll sections. Therefore, if you want to switch section unofficially (we do not have the ability to switch your official enrollment through GOLD), please follow the steps at <a href="https://docs.google.com/spreadsheets/d/1PYbA5KcPH4GcTeA1bRHboyW3D8kwBBq2gJFsY9fZreU/edit?usp=sharing" target = "_blank">this</a> link. Any requests to switch sections that do not adhere to the guidelines posted at that link will be ignored.

## Email Policy

If you need to send an email to me (Ethan), please include "PSTAT 5A" in the subject line of your email. Additionally, please allow up to one business day for a reply (though I will do my best to get back to you ASAP) Please note that I do not answer questions with extensive mathematics/equations over email (as trying to communicate in math over email can be a bit of a technical nightmare) Instead, if you have questions relating to course content I welcome you to either ask over <a href = "https://discord.gg/5VbwUVjAKg" target = "_blank">Discord</a> or during one of my Office Hours. Also, should you need to include your TA, please send a **single** email to both your TA and myself, as opposed to separate emails to the two of us. Thank you!

## Disclaimer

The instructor reserves the right to modify this syllabus if he deems such modifications academically advisable. Such modifications, should they occur, will be announced publicly.
